version: '3.8'

services:
  siem-db:
    image: postgres:15-alpine
    container_name: siem-postgres
    environment:
      POSTGRES_DB: siem_console
      POSTGRES_USER: siem_admin
      POSTGRES_PASSWORD: SecureNetwork!2026
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - siem-network

  backend:
    build:
      context: ./demo
      dockerfile: Dockerfile
    container_name: siem-backend
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - siem-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://siem-db:5432/siem_console
    networks:
      - siem-network

  frontend:
    build:
      context: ./network-ui
      dockerfile: Dockerfile
    container_name: siem-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - siem-network

  # YENİ EKLENEN SERVİSLER
  prometheus:
    image: prom/prometheus:latest
    container_name: siem-prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - siem-network

  grafana:
    image: grafana/grafana:latest
    container_name: siem-grafana
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - siem-network

volumes:
  postgres_data:

networks:
  siem-network:
    driver: bridge