# Web sunucusunun çalışacağı port
server.port=8080

# PostgreSQL Veri Tabanı Ayarları (Docker Compose'daki siem-db servisine bağlanır)
spring.datasource.url=jdbc:postgresql://siem-db:5432/siem_console
spring.datasource.username=siem_admin
spring.datasource.password=SecureNetwork!2026
spring.datasource.driverClassName=org.postgresql.Driver

# JPA & Hibernate Ayarları
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# İzleme ve Metrik Ayarları
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always