# Web sunucusunun çalışacağı port
server.port=8080

# H2 Veri Tabanı Ayarları
spring.datasource.url=jdbc:h2:mem:networkdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Veri tabanı tablolarını otomatik oluştur/güncelle
spring.jpa.hibernate.ddl-auto=update

# H2'nin web arayüzüne erişim izni (Verileri tarayıcıdan görmek için)
spring.h2.console.enabled=true