-- Baseline schema, captured verbatim from the schema Hibernate (ddl-auto=update)
-- was already producing for the existing Device and AuditLog entities, via:
--   docker compose exec siem-db pg_dump -U <user> -d siem_console --schema-only
-- This migration establishes that exact schema as the Flyway baseline so existing
-- data is not touched when ddl-auto switches to validate.

CREATE TABLE audit_log (
    id        bigint NOT NULL,
    message   character varying(255),
    "timestamp" timestamp(6) without time zone,
    CONSTRAINT audit_log_pkey PRIMARY KEY (id)
);

ALTER TABLE audit_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE device (
    id          bigint NOT NULL,
    device_type character varying(255),
    ip_address  character varying(255),
    latency     bigint,
    name        character varying(255),
    status      character varying(255),
    CONSTRAINT device_pkey PRIMARY KEY (id)
);

ALTER TABLE device ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME device_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
