-- Incident lifecycle schema.
--
-- Also creates correlation_rule here rather than in its own migration: the next
-- migration is reserved for the built-in rule rows, and a seed insert cannot run
-- before the table it targets exists.
--
-- Identity column syntax mirrors V1__baseline.sql so every generated key in this
-- schema behaves the same way.
--
-- incident.source_device_id is a plain column, not a foreign key: an incident is
-- a historical record and has to outlive the device that caused it. Deleting a
-- decommissioned host must not erase the reason it was investigated.

CREATE TABLE incident (
    id                 bigint                      NOT NULL,
    title              character varying(255)      NOT NULL,
    description        character varying(2000),
    severity           character varying(32)       NOT NULL,
    status             character varying(32)       NOT NULL,
    source_device_id   bigint,
    mitre_technique_id character varying(32),
    assignee           character varying(255),
    created_at         timestamp(6) with time zone NOT NULL,
    updated_at         timestamp(6) with time zone NOT NULL,
    CONSTRAINT incident_pkey PRIMARY KEY (id)
);

ALTER TABLE incident ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME incident_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- The console's default view is "open incidents, worst first, newest first".
CREATE INDEX idx_incident_status ON incident (status);
CREATE INDEX idx_incident_severity ON incident (severity);
CREATE INDEX idx_incident_created_at ON incident (created_at);
CREATE INDEX idx_incident_source_device_id ON incident (source_device_id);

CREATE TABLE incident_comment (
    id          bigint                      NOT NULL,
    incident_id bigint                      NOT NULL,
    author      character varying(255)      NOT NULL,
    body        character varying(2000)     NOT NULL,
    created_at  timestamp(6) with time zone NOT NULL,
    CONSTRAINT incident_comment_pkey PRIMARY KEY (id)
);

ALTER TABLE incident_comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME incident_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE INDEX idx_incident_comment_incident_id ON incident_comment (incident_id);

-- Correlation rules are configuration, stored as rows so the shipped rule set
-- can be tuned or disabled without a rebuild. condition_json carries a "type"
-- discriminator plus type-specific parameters; the two parameters every type
-- shares (how many, over how long) are hoisted into their own columns so they
-- can be queried and edited without rewriting the JSON.
CREATE TABLE correlation_rule (
    id              bigint                      NOT NULL,
    name            character varying(255)      NOT NULL,
    enabled         boolean                     NOT NULL,
    condition_json  character varying(2000)     NOT NULL,
    threshold_count integer                     NOT NULL,
    window_seconds  integer                     NOT NULL,
    severity        character varying(32)       NOT NULL,
    created_at      timestamp(6) with time zone NOT NULL,
    CONSTRAINT correlation_rule_pkey PRIMARY KEY (id)
);

ALTER TABLE correlation_rule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME correlation_rule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE INDEX idx_correlation_rule_enabled ON correlation_rule (enabled);
