-- Normalised events accepted from external producers.
--
-- occurred_at (what the producer claims) and received_at (what this service
-- observed) are separate columns on purpose: keeping both makes clock skew on
-- the sending side visible instead of silently rewriting the timeline.

CREATE TABLE ingested_event (
    id          bigint                      NOT NULL,
    source      character varying(255)      NOT NULL,
    category    character varying(255)      NOT NULL,
    severity    character varying(32)       NOT NULL,
    raw_payload character varying(8000),
    occurred_at timestamp(6) with time zone NOT NULL,
    received_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT ingested_event_pkey PRIMARY KEY (id)
);

ALTER TABLE ingested_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ingested_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Investigation nearly always starts from "what else did this source send", and
-- the live event stream is ordered by time.
CREATE INDEX idx_ingested_event_source ON ingested_event (source);
CREATE INDEX idx_ingested_event_occurred_at ON ingested_event (occurred_at);
CREATE INDEX idx_ingested_event_severity ON ingested_event (severity);
