-- Console operators.
--
-- Table is "app_user", not "user": the bare word is a reserved identifier in
-- PostgreSQL and every statement touching it would need to be quoted, which is
-- a trap that only shows up once a query is written by hand instead of by the
-- ORM. Same reasoning that already produced "correlation_rule" instead of "rule".
--
-- Only the bcrypt digest of the password is stored. The bootstrap account
-- itself is not seeded here: a digest checked into a migration is a published
-- password for every deployment that ever runs it. AdminUserBootstrap creates
-- the first operator at application startup instead, from an environment
-- variable, and never writes it to a file that ends up in version control.

CREATE TABLE app_user (
    id            bigint                 NOT NULL,
    username      character varying(64)  NOT NULL,
    password_hash character varying(255) NOT NULL,
    role          character varying(16)  NOT NULL,
    enabled       boolean                NOT NULL,
    CONSTRAINT app_user_pkey PRIMARY KEY (id),
    CONSTRAINT uq_app_user_username UNIQUE (username)
);

ALTER TABLE app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
