-- History of device reachability-probe latency readings, one row per
-- checkDeviceStatus(Long) call that measures a latency. Used to serve
-- GET /api/v1/devices/{id}/latency so the console can chart latency over
-- time instead of only showing the device's current value.
--
-- device_id is a plain column, not a foreign key: the existing device table
-- (see V1__baseline.sql) predates this migration and this history is allowed
-- to outlive an individual device's row without cascading rules to worry
-- about, matching the sourceDeviceId columns already used on incident and
-- ingested_event (see V2__incidents.sql, V4__ingested_events.sql).

CREATE TABLE latency_sample (
    id          bigint NOT NULL,
    device_id   bigint NOT NULL,
    latency     bigint NOT NULL,
    recorded_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT latency_sample_pkey PRIMARY KEY (id)
);

ALTER TABLE latency_sample ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME latency_sample_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Serves "latest N samples for a device", the only read pattern the history
-- endpoint has.
CREATE INDEX idx_latency_sample_device_recorded_at
    ON latency_sample (device_id, recorded_at DESC);
